### ISSUE TITLE
Updated 1.1.3 doesn't seem to remove any issues.

### ISSUE THREAD

**Issue by JosueNinolibre** [im-open/cleanup-deployment-board#17]
I was reviewing some of the changes we made to be up to date with update deployment board workflow because of the recent graphql error causing it not work properly. 

It seems that it currently does not recognize that we have a myriad of issues open that are posted to our board.

Below is a recent run of our workflow with v1.1.3, It currently says we do not have any issues.

> Run im-open/cleanup-deployment-board@v1.1.[3](https://github.com/im-client/client-implementations-ui/actions/runs/4300251694/jobs/7496275766#step:2:3)
  with:
    github-token: ***
    board-number: 1
    branch-cleanup-strategy: number
    branch-threshold: [5](https://github.com/im-client/client-implementations-ui/actions/runs/4300251694/jobs/7496275766#step:2:5)
    tag-cleanup-strategy: number
    tag-threshold: 5
    sha-cleanup-strategy: number
    sha-threshold: 5
    github-login: github-actions
>The im-client/client-implementations-ui repository does not appear to have any issues.
>There were no active Branch cards to cleanup.
>There were no active Tag cards to cleanup.
>There were no active SHA cards to cleanup.

If this is based off of the issue tab, we currently have 94 issues open and those also still show on our board. [See Our Deployment Board](https://github.com/im-client/client-implementations-ui/projects/1)

Image of the issue tab:
![2023-02-28_22h20_51](https://user-images.githubusercontent.com/72095056/222052088-13e0ea06-9eee-4bbe-9d88-b386a843281b.png)

**Comment by danielle-casella-adams** [comment]
There was an issue when the GitHub API was updated a few weeks ago but this should be resolved now.  It won't cleanup the duplicated items until they have aged/numbered out but once that condition is met, the action should clean them up.
